language: bash

sudo: required

services:
  - docker

cache:
  -  ${HOME}/google-cloud-sdk

before_install:
  - |
    if [[ ! -f "${HOME}/google-cloud-sdk/bin/gcloud" ]]; then
      rm -rf "${HOME}/google-cloud-sdk"
      curl -L https://sdk.cloud.google.com | bash > /dev/null
    fi

script:
  - ./ci/build.sh && ./ci/deploy.sh

env:
  global:
  - PATH="${HOME}/google-cloud-sdk/bin:${PATH}"
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
