version: "3"
services:
  report-server:
    image: akvo/akvo-reportserver:latest
    depends_on:
      - db
    command: /opt/run.sh
    volumes:
      - /tmp/reportserver:/tmp
  test:
    build: test
    command: tail -f /dev/null
    volumes:
      - /tmp/reportserver:/tmp
