version: "3"
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=reportserver
      - POSTGRES_PASSWORD=reportserver
      - POSTGRES_DB=reportserver
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:ro
  report-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: /opt/run.sh
