version: "3"
services:
  report-server:
    image: akvo/akvo-reportserver:latest
    volumes:
      - /tmp/reportserver:/tmp
  test:
    build: test
    command: tail -f /dev/null
    volumes:
      - /tmp/reportserver:/tmp
