version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=reportserver
      - POSTGRES_PASSWORD=reportserver
      - POSTGRES_DB=reportserver
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:ro
  report-server:
    environment:
      - RS_DB_USER=reportserver
      - RS_DB_PASSWORD=reportserver
      - RS_DB_NAME=reportserver
      - RS_DB_HOST=db
    depends_on:
      - db
    command: /opt/run.sh
