apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reportserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: reportserver
  template:
    metadata:
      labels:
        run: reportserver
        akvo-report-server-version: ${TRAVIS_COMMIT}
        app: reportserver
    spec:
      containers:
      - name: reportserver
        image: akvo/akvo-reportserver:${TRAVIS_COMMIT}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 180
        env:
        - name: RS_DB_USER
          valueFrom:
            secretKeyRef:
              name: reportserver
              key: rs_db_user
        - name: RS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reportserver
              key: rs_db_password
        - name: RS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: reportserver
              key: rs_db_name
        - name: RS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: reportserver
              key: rs_db_host
        - name: RS_PBE_SALT
          valueFrom:
            secretKeyRef:
              name: reportserver
              key: rs_pbe_salt
        - name: RS_PBE_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: reportserver
              key: rs_pbe_passphrase
        - name: RS_HMAC_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: reportserver
              key: rs_hmac_passphrase
        - name: RS_EXTRA_FONT_URL
          valueFrom:
            secretKeyRef:
              name: reportserver
              key: rs_extra_font_url
